config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
      sessions: 'admins/sessions'
      }
  devise_for :users, controllers:{
        sessions: 'users/sessions'
      }
    
    devise_scope :admin do
       get "admins/users/lista",
       to: "admins/sessions#lista",
       as: "users_list"    
    end    
  resources :nuevos
  
  resources :zombies do
      resources :brains
  end      
    
    root to: 'zombies#index'
  #get "sexto_repo/cerebros", to: 'brains#index', as: 'brains'    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/nuevo.rb
class Nuevo < ApplicationRecord
end

app/controllers/nuevos_controller.rb
class NuevosController < ApplicationController
  before_action :set_nuevo, only: [:show, :edit, :update, :destroy]

  # GET /nuevos
  # GET /nuevos.json
  def index
    @nuevos = Nuevo.all
  end

  # GET /nuevos/1
  # GET /nuevos/1.json
  def show
  end

  # GET /nuevos/new
  def new
    @nuevo = Nuevo.new
  end

  # GET /nuevos/1/edit
  def edit
  end

  # POST /nuevos
  # POST /nuevos.json
  def create
    @nuevo = Nuevo.new(nuevo_params)

    respond_to do |format|
      if @nuevo.save
        format.html { redirect_to @nuevo, notice: 'Nuevo was successfully created.' }
        format.json { render :show, status: :created, location: @nuevo }
      else
        format.html { render :new }
        format.json { render json: @nuevo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nuevos/1
  # PATCH/PUT /nuevos/1.json
  def update
    respond_to do |format|
      if @nuevo.update(nuevo_params)
        format.html { redirect_to @nuevo, notice: 'Nuevo was successfully updated.' }
        format.json { render :show, status: :ok, location: @nuevo }
      else
        format.html { render :edit }
        format.json { render json: @nuevo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nuevos/1
  # DELETE /nuevos/1.json
  def destroy
    @nuevo.destroy
    respond_to do |format|
      format.html { redirect_to nuevos_url, notice: 'Nuevo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nuevo
      @nuevo = Nuevo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nuevo_params
      params.require(:nuevo).permit(:fuerza)
    end
end

app/helpers/nuevos_helper.rb
module NuevosHelper
end

app/views/nuevos/_form.html.erb
<%= form_for(nuevo) do |f| %>
  <% if nuevo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nuevo.errors.count, "error") %> prohibited this nuevo from being saved:</h2>

      <ul>
      <% nuevo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fuerza %>
    <%= f.number_field :fuerza %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nuevos/edit.html.erb
<h1>Editing Nuevo</h1>

<%= render 'form', nuevo: @nuevo %>

<%= link_to 'Show', @nuevo %> |
<%= link_to 'Back', nuevos_path %>

app/views/nuevos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Nuevos</h1>

<table>
  <thead>
    <tr>
      <th>Fuerza</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nuevos.each do |nuevo| %>
      <tr>
        <td><%= nuevo.fuerza %></td>
        <td><%= link_to 'Show', nuevo %></td>
        <td><%= link_to 'Edit', edit_nuevo_path(nuevo) %></td>
        <td><%= link_to 'Destroy', nuevo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nuevo', new_nuevo_path %>

app/views/nuevos/new.html.erb
<h1>New Nuevo</h1>

<%= render 'form', nuevo: @nuevo %>

<%= link_to 'Back', nuevos_path %>

app/views/nuevos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fuerza:</strong>
  <%= @nuevo.fuerza %>
</p>

<%= link_to 'Edit', edit_nuevo_path(@nuevo) %> |
<%= link_to 'Back', nuevos_path %>