config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{
      sessions: 'admins/sessions'
      }
  devise_for :users, controllers:{
        sessions: 'users/sessions'
      }
    
    devise_scope :admin do
       get "admins/users/lista",
       to: "admins/sessions#lista",
       as: "users_list"    
    end    
  resources :nuevos
  
  resources :zombies do
      resources :brains
  end      
    
    root to: 'zombies#index'
  #get "sexto_repo/cerebros", to: 'brains#index', as: 'brains'    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sextoa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Jikus APP</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown"  aria-expanded="true">
          Zombie
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" ><%= link_to 'Lista Zombie', zombies_path %></a>
          <a class="dropdown-item" href="#"><%= link_to 'Nuevo Zombie', new_zombie_path %></a>
        </div>
        
      </li>
      <li class=" navbar-toggler-right">
          <%if user_signed_in?%>
              <strong>Bienvenido(a) <%=current_user.email%></strong>
              <strong><%=link_to "Cerrar sesion", destroy_user_session_path, method: :delete%></strong> 
              <strong><%=link_to "Editar perfil", edit_user_registration_path%></strong>
                   
          <%elsif admin_signed_in?%>
              <strong>Bienvenido(a) <%=current_admin.email%></strong>
              <strong><%=link_to "Cerrar sesion", destroy_admin_session_path, method: :delete%></strong> 
             
          <% else %>
                <strong><%=link_to "Login", new_user_session_path%></strong>
                <strong><%=link_to "Registrarse", new_user_registration_path%></strong>
          <%end%> 
          
      </li>
    </ul>
  </div>
</nav>
   <% if notice%>
       <p class="alert alert-success"><%=notice%></p>
    <%end%>
    <% if alert%>
        <p class="alert alert-danger"><%=alert%></p>
    <%end%>      
    <%= yield %>
      
  </body>
</html>